# .github/workflows/c-cpp.yml
name: C++ CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++
    - name: Clean previous builds
      run: |
        rm -rf build/
    - name: Configure CMake
      run: cmake -B build -S .
    - name: Build with CMake
      run: cmake --build build --config Release
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: calculator-linux
        path: build/calculator

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        choco install cmake
    - name: Clean previous builds
      run: |
        if (Test-Path build) { rm -Recurse -Force build }
    - name: Configure CMake
      run: cmake -B build -S .
    - name: Build with CMake
      run: cmake --build build --config Release
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: calculator-windows
        path: build/Release/calculator.exe

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        brew install cmake
    - name: Clean previous builds
      run: |
        rm -rf build/
    - name: Configure CMake
      run: cmake -B build -S .
    - name: Build with CMake
      run: cmake --build build --config Release
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: calculator-macos
        path: build/calculator

  release:
    runs-on: ubuntu-latest
    needs: [build-ubuntu, build-windows, build-macos]
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/calculator-linux/calculator
          artifacts/calculator-windows/calculator.exe
          artifacts/calculator-macos/calculator