# .github/workflows/c-cpp.yml
name: C++ CI

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Compile on Ubuntu
      run: |
        sudo apt-get install -y g++
        g++ -std=c++17 main_cli.cpp string_processing.cpp -o calculator -static
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: calculator-linux
        path: calculator

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Compile on Windows
      run: g++ -std=c++17 main_cli.cpp string_processing.cpp -o calculator.exe -static
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: calculator-windows
        path: calculator.exe

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Compile on macOS
      run: |
        g++ -std=c++17 main_cli.cpp string_processing.cpp -o calculator -static
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: calculator-macos
        path: calculator

  release:
    runs-on: ubuntu-latest
    needs: [build-ubuntu, build-windows, build-macos]
    if: startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: write

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          artifacts/calculator-linux/calculator
          artifacts/calculator-windows/calculator.exe
          artifacts/calculator-macos/calculator
