# .github/workflows/build.yml
name: C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Compile on Ubuntu
      run: |
        sudo apt update
        sudo apt install -y MinGW64
        g++ -std=c++17 main_cli.cpp string_processing.cpp -o calculator
        ./calculator --version # Optional: run a simple check if the executable supports it

  
  build-windows:
    runs-on: windows-latest

    steps:
     - name: Checkout repository
     - uses: actions/checkout@v3

      - name: Setup MSYS2 and install g++
      - uses: msys2/setup-msys2-action@v2
        with:
          msystem: MINGW64
          path-type: strict
          update: true
          # 仅安装 g++ 工具链
          install: mingw-w64-x86_64-toolchain
      - name: Compile on Windows
        shell: msys2 {0}
          run: |
        g++ -std=c++17 main_cli.cpp string_processing.cpp -o calculator.exe
        .\calculator.exe --version # Optional: run a simple check if the executable supports it

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Compile on macOS
      run: |
        g++ -std=c++17 main_cli.cpp string_processing.cpp -o calculator
        ./calculator --version # Optional: run a simple check if the executable supports it
